name = "apollogallery"
compatibility_date = "2024-11-27"
compatibility_flags = [ "nodejs_compat" ]
send_metrics = false
preview_urls = false
workers_dev = false
main = "dist/_worker.js"

# Set up assets binding to migrate from pages to workers
assets = { directory = "./dist/", binding = "ASSETS", html_handling = "drop-trailing-slash", not_found_handling = "404-page", run_worker_first = true }

# Domain for the website
routes = [
  { pattern = "apollo.dog", custom_domain = true },
  { pattern = "www.apollo.dog", custom_domain = true }
]

[[r2_buckets]]
binding = "R2"
bucket_name = "apollogallery-bucket"

[[d1_databases]]
binding = "DB"
database_name = "apollo-gallery"
database_id = "4c573785-5d56-4154-9dd2-4517c2e00779"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "ec290df347654a639feecda9c0b077c4"

[triggers]
crons = ["0 0 * * *"]

[secrets]
required=["PASSWORD"]

#----------------------------------------------------------- CONFIG

[vars]

# Page title
PAGE_TITLE = "Apollo's Gallery"

# Default Page Description
DESCRIPTION = "Cute Shiba Inu pictures daily! See his amazing adventures and check back for updates!"

# Image transformations
IMGT = "true"

# Admin Panel Credentials uncomment to set here | commented to set using cf dashboard
USERNAME = "admin"

# Allow for not using the KV cache method
USE_CACHE = "true"

# Copyright attribution name
COPYRIGHT = "SocksTheWolf"

# Kofi Username (leave empty if you do not want to add a kofi support widget)
KOFI_USERNAME = "SocksTheWolf"

# Color scheme used for CSS
# Valid color names can be found here: https://picocss.com/docs/colors
COLOR_SCHEME = "orange"

# Path to the gallery application 
# (should contain no slashes, unless this serves on root, which then it should be a single slash)
GALLERY_PATH = "/"