name = "apollogallery"
compatibility_date = "2024-11-27"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]


[[r2_buckets]]
binding = "R2"
bucket_name = "apollogallery-bucket"

[[d1_databases]]
binding = "DB"
database_name = "apollo-gallery"
database_id = "4c573785-5d56-4154-9dd2-4517c2e00779"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "ec290df347654a639feecda9c0b077c4"

#----------------------------------------------------------- CONFIG

[vars]

# Page title
PAGE_TITLE = "Apollo Gallery"

# Image transformations
IMGT = "false"

# Admin Panel Credentials unsoment to set here | commented to set using cf dashboard
USERNAME = "admin"

# Allow for not using the KV cache method
USE_CACHE="true"

# Copyright attribution name
COPYRIGHT="SocksTheWolf"